import pic1 from "./assets/images/pic1.jpg";
import pic2 from "./assets/images/pic2.jpg";
import pic3 from "./assets/images/pic3.jpg";
import pic4 from "./assets/images/pic4.jpg";
import pic5 from "./assets/images/pic5.jpg";
import pic6 from "./assets/images/pic6.jpg";
import pic7 from "./assets/images/pic7.jpg";
import pic8 from "./assets/images/pic8.jpg";
import pic9 from "./assets/images/pic9.jpg";
import pic10 from "./assets/images/manuDibango.png";
import pic12 from "./assets/images/pic12.jpg";
import pic13 from "./assets/images/locko.jpg";
import pic14 from "./assets/images/charlote.jpg";
import pic15 from "./assets/images/petit.jpg";
import pic16 from "./assets/images/ladyPonce.jpg";
import pic17 from "./assets/images/mrLeo.jpg";
import pic18 from "./assets/images/Salatiel.jpeg";
import pic19 from "./assets/images/ko-c.jpg";

export const ARTISTS = {
  artists: [
    {
      id: 1,
      name: "KO-c",
      region: "Southwest",
      niche: "Afrobeat",
      price: 5000,
      image: pic19,
      description: "Legendary Cameroonian Afrobeat Singer",
      cowries: 0,
      reviews: [],
    },
    {
      id: 2,
      name: "Charlotte Dipanda",
      region: "Centre",
      niche: "Afropop",
      price: 3500,
      image: pic14,
      description: "Soulful singer known for her emotional ballads",
      cowries: 0,
      reviews: [],
    },
    {
      id: 3,
      name: "Petit Pays",
      region: "Littoral",
      niche: "Makossa",
      price: 4000,
      image: pic15,
      description: "Energetic performer and makossa innovator",
      cowries: 0,
      reviews: [],
    },
    {
      id: 4,
      name: "Manu Dibango",
      region: "center",
      niche: "makossa",
      price: 6000,
      image: pic10,
      description: "Legendary Saxophonists",
      cowries: 0,
      reviews: [],
    },
    {
      id: 5,
      name: "Dynastie Le Tigre",
      region: "West",
      niche: "Bikutsi",
      price: 3000,
      image: pic5,
      description: "Dynamic performer of traditional Beti rhythms",
      cowries: 0,
      reviews: [],
    },
    {
      id: 6,
      name: "Lapiro de Mbanga",
      region: "Littoral",
      niche: "Mboko",
      price: 3500,
      image: pic6,
      description: "Socially conscious singer and guitarist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 7,
      name: "Kareyce Fotso",
      region: "Adamawa",
      niche: "Folk",
      price: 2800,
      image: pic7,
      description: "Talented singer-songwriter with a unique voice",
      cowries: 0,
      reviews: [],
    },
    {
      id: 8,
      name: "Ekambi Brillant",
      region: "South",
      niche: "Makossa",
      price: 4500,
      image: pic8,
      description: "Veteran makossa artist with a golden voice",
      cowries: 0,
      reviews: [],
    },
    {
      id: 9,
      name: "Coco Argentée",
      region: "Centre",
      niche: "Bikutsi",
      price: 3200,
      image: pic9,
      description: "Vibrant performer of modern bikutsi",
      cowries: 0,
      reviews: [],
    },
    {
      id: 10,
      name: "Franck Biyong",
      region: "Centre",
      niche: "Bikutsi",
      price: 3800,
      image: pic1,
      description: "Innovative guitarist blending funk and African rhythms",
      cowries: 0,
      reviews: [],
    },
    {
      id: 11,
      name: "Locko",
      region: "Southwest",
      niche: "Afropop",
      price: 3000,
      image: pic13,
      description: "Rising star in the Cameroonian pop scene",
      cowries: 0,
      reviews: [],
    },
    {
      id: 12,
      name: "Blick Bassy",
      region: "Centre",
      niche: "Bikutsi",
      price: 3500,
      image: pic3,
      description: "Soulful singer preserving the Bassa language through music",
      cowries: 0,
      reviews: [],
    },
    {
      id: 13,
      name: "Mama Nguea",
      region: "Littoral",
      niche: "Makossa",
      price: 4000,
      image: pic4,
      description: "Iconic female makossa artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 14,
      name: "Salatiel",
      region: "Southwest",
      niche: "Afrobeats",
      price: 3500,
      image: pic18,
      description: "Multi-talented producer and performer",
      cowries: 0,
      reviews: [],
    },
    {
      id: 15,
      name: "Sally Nyolo",
      region: "South",
      niche: "Jazz",
      price: 4200,
      image: pic6,
      description: "Former Zap Mama member with a unique musical style",
      cowries: 0,
      reviews: [],
    },
    {
      id: 16,
      name: "Kristo Numpuby",
      region: "Far North",
      niche: "Jazz",
      price: 3800,
      image: pic7,
      description:
        "Guitarist and composer blending African and Western influences",
      cowries: 0,
      reviews: [],
    },
    {
      id: 17,
      name: "Lady Ponce",
      region: "Centre",
      niche: "Bikutsi",
      price: 3500,
      image: pic16,
      description: "Energetic bikutsi performer known for her stage presence",
      cowries: 0,
      reviews: [],
    },
    {
      id: 18,
      name: "Askia",
      region: "North",
      niche: "Jazz",
      price: 2800,
      image: pic9,
      description:
        "Talented rapper pushing the boundaries of Cameroonian hip-hop",
      cowries: 0,
      reviews: [],
    },
    {
      id: 19,
      name: "Koppo",
      region: "West",
      niche: "Makossa",
      price: 3000,
      image: pic7,
      description: "Pioneering Rapper known for his witty lyrics",
      cowries: 0,
      reviews: [],
    },
    {
      id: 20,
      name: "Blaise B",
      region: "Southwest",
      niche: "Afrobets",
      price: 5000,
      image: pic2,
      description: "Popular highlife and Afrobeats artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 21,
      name: "Shweng King",
      region: "Northwest",
      niche: "Jazz",
      price: 5000,
      image: pic2,
      description: "Popular Jazz and Afrobeats artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 22,
      name: "Flavour N'abania",
      region: "Southwest",
      niche: "Afropop",
      price: 5000,
      image: pic2,
      description: "Popular highlife and Afrobeats artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 23,
      name: "Nora Sama",
      region: "Southwest",
      niche: "Afropop",
      price: 5000,
      image: pic12,
      description: "Popular Afropop and Afrobeats artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 24,
      name: "Mr Leo",
      region: "Southwest",
      niche: "Afropop",
      price: 4000,
      image: pic17,
      description: "Iconic Male Afropop artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 25,
      name: "Flavour N'abania",
      region: "Southwest",
      niche: "Afropop",
      price: 5000,
      image: pic2,
      description: "Popular highlife and Afrobeats artist",
      cowries: 0,
      reviews: [],
    },
    {
      id: 26,
      name: "Grand Barack",
      region: "Littoral",
      niche: "Makossa",
      price: 4000,
      image: pic12,
      description: "Energetic performer and makossa innovator",
      cowries: 0,
      reviews: [],
    },
    {
      id: 26,
      name: "Boss k",
      region: "North",
      niche: "Jazz",
      price: 4000,
      image: pic12,
      description: "Energetic performer and makossa innovator",
      cowries: 0,
      reviews: [],
    },
  ],
};
